language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt
  - pip install -q flake8

script:
  - flake8 .
  - python3 VB_diarization_demo.py

notifications:
  email: false

branches:
  only:
    - master
